---
- name: "Fedora : Update and repositroy configuration."
  hosts:  all
  
  tasks:
    - name: Update OS packages.
      become: true
      ansible.builtin.dnf:
        update_cache: yes

    - name: Add Hashicorp repository.
      become: true
      ansible.builtin.yum_repository:
        name: hashicorp 
        description: Hashcicorp tools repository.  
        baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
        gpgcheck: true
        gpgkey: https://rpm.releases.hashicorp.com/gpg 
        enabled: true
          

    - name: Add Docker repository.
      become: true
      ansible.builtin.yum_repository:
        name: docker 
        description: Docker repository.
        baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/fedora/gpg 
        enabled: true
          

- name: "Fedora : Setting user configuration."          
  hosts: all
  
  tasks:
    - name : "Creating symbolic links."    
      ansible.builtin.file:
        src: ""
        dest: ""          
        owner:
        group:
        state: link          


- name: "Fedora : Install packages."
  hosts: all

  tasks:
    - name: Install packages.
      become: true
      ansible.builtin.dnf:
        name:
          - asciidoctor
          - azure-cli
          - bat
          - dnf-plugins-core
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
          - docker-compose
          - exa
          - fish
          - gnome-tweak-tool
          - gnome-extensions-app
          - golang
          - keepassxc
          - nodejs
          - powerline 
          - powerline-fonts
          - python3
          - python3-virtualenv
          - python3-notebook 
          - mathjax 
          - sscg
          - terraform
          - vim
          - vim-powerline
        state: latest
            

