--- 
- name: "Fedora : Update and repositroy configuration."
  hosts:  all
    #gather_facts: no
  
  tasks:
  - name: Update OS packages
    become: true
    ansible.builtin.dnf:
      update_cache: yes

  - name: Add Hashicorp repository
    become: true
    ansible.builtin.yum_repository:
      name: hashicorp 
      description: Hashcicorp tools repository.  
      baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
      gpgcheck: true
      gpgkey: https://rpm.releases.hashicorp.com/gpg 
      enabled: true
        

  - name: Add Docker repository
    become: true
    ansible.builtin.yum_repository:
      name: docker 
      description: Docker repository
      baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/fedora/gpg 
      enabled: true
        

- name: "Fedora : Setting user configuration."          
  hosts: all
  
  tasks:
  - name : Creating symbolic links    
    ansible.builtin.file:
      src: "~/{{ item.src }}"
      dest: "~/{{ item.dest }}"          
      state: link          
    with_items:
      - { src: "Desktop", dest: "desktop" } 
      - { src: "Documents", dest: "documents" } 
      - { src: "Downloads", dest: "downloads" } 
      - { src: "Music", dest: "music" } 
      - { src: "Pictures", dest: "pictures" } 
      - { src: "Templates", dest: "templates" } 
      - { src: "Videos", dest: "videos" } 

  - name: "Creating directories"
    ansible.builtin.file:
      path: "{{ item.directory }}"
      state: directory          
    with_items:
      - directory: "~/projects"        
      - directory: "~/.config"

- name: "Fedora : Install packages"
  hosts: all

  tasks:
  - name: Install rpm packages
    become: true
    ansible.builtin.dnf:
      name:
        - asciidoctor
        - azure-cli
        - bat
        - dnf-plugins-core
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
        - docker-compose
        - exa
        - fish
        - feh
        - gnome-tweak-tool
        - gnome-extensions-app
        - golang
        - i3
        - keepassxc
        - nodejs
        - powerline 
        - powerline-fonts
        - python3
        - python3-virtualenv
        - python3-notebook 
        - mathjax 
        - sscg
        - terraform
        - tldr
        - vim
        - vim-powerline
      state: latest

- name: Docker Setup          
  hosts: all

  tasks:
  - name: Enabled docker service
    become: true
    ansible.builtin.service:
      name: docker
      enabled: true          
      state: started

  - name: Create docker group
    ansible.builtin.group:
      name: docker

  - name: Adding default user to docker group
    become: true
    ansible.builtin.user:
      name: salvor
      groups: docker
      append: yes

